apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cleanup-script-configmap
data: 
  mongo-db-cleanup-script.sh: |
      #!/bin/bash
    
      USERNAME=$MONGODB_USERNAME
      PASSWORD=$MONGODB_PASSWORD
      DB_URL=$MONGODB_URL
      DB_NAME=$DB_NAME
        
      # MongoDB Atlas connection string (replace with your connection string)
      MONGO_URI="mongodb+srv://$USERNAME:$PASSWORD@$DB_URL/$DB_NAME"
        
      # List of collections to delete (replace with actual collection names)
      COLLECTIONS=$(mongosh "$MONGO_URI" --quiet --eval "db.getCollectionNames().join(' ')")
        
      # Loop through collections and delete each one of them present inside that database.
      for COLLECTION in $COLLECTIONS
      do
        echo "Deleting collection: $COLLECTION"
        mongosh "$MONGO_URI" --eval "db.$COLLECTION.drop()"
      done
        
      echo "Collections deleted successfully!"
