apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-db-cleanup
  labels:
     app: mongo-db-cleanup
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: mongo-db-cleanup-script
          configMap:
             name: db-cleanup-script-configmap
      containers:
        - name: <+serviceVariable.ContainerName>
          image: <+serviceVariable.Image>
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-auth
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-auth
                  key: password      
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-db-auth
                  key: server_url
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-auth
                  key: db_name  
          volumeMounts:
             - name: mongo-db-cleanup-script
               mountPath: scripts/
          command:
             - "sh"
             - "-c"
          args:
            - "sh -x scripts/mongo-db-cleanup-script.sh; sleep infinity"
